### PR TITLE
Remove pk-server conf as ununsed in practice.  Add websocket-secure

### PR DESCRIPTION
**Pull request by bp1222**

### CODE REVIEW

**Review by mattdodge — CHANGES_REQUESTED** [review]
I don't think we should remove the pk server stuff. I don't think that is unused in practice. If someone wanted to quickly launch and run an instance locally I would assume they would use the local/built-in pubkeeper server.

**Comment by bp1222** [comment]
Although we are not providing any binary with the pk-server component installed.  I'd assume when/if we do could add that part back in.

**Comment by mattdodge** [comment]
If that's not the case then we should add that component to binary deployment. This repo should be in a state that someone can pull it and run nio and have it work. We have documentation that provides those instructions. Including the pk server component seems to be the fastest way for someone local to get nio up and running.

**Comment by bp1222** [comment]
I'll re-add back in, and build the nio-full binary with the pk-server component.

**Review by mattdodge — APPROVED** [review]
Changed the disabled line to comma separated but everything else looks good

**Pull request merged**
